# Generated by Django 4.0 on 2023-10-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_material_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, upload_to='materials/'),
        ),
    ]
