# Generated by Django 4.0 on 2023-10-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_material_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
